Cuatri 3/Portafolio2/Avance2/System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

Cuatri 3/Portafolio2/Avance2/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    
    path('list/Areas-de-Trabajo/', views.AreasTrabajo.as_view(), name="AreasTrabajo"),
    path('Detail/Areas-de-Trabajo/<int:pk>/', views.DetailAreasTrabajo.as_view(), name='DetailAT'),
    path('Create/Areas-de-Trabajo/', views.CreateAreaTrabajo.as_view(), name='CreateAT'),
    path('Update/Areas-de-Trabajo/<int:pk>/', views.UpdateAreaTrabajo.as_view(), name='UpdateAT'),
    path('Delete/Areas-de-Trabajo/<int:pk>/', views.DeleteAreaTrabajo.as_view(), name='DeleteAT'),

    path('list/Empleados/', views.Empleado.as_view(), name="Empleados"),
    path('Detail/Empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='DetailE'),
    path('Create/Empleado/', views.CreateEmpleado.as_view(), name='CreateE'),
    path('Update/Empleado/<int:pk>/', views.UpdateEmpleado.as_view(), name='UpdateE'),
    path('Delete/Empleado/<int:pk>/', views.DeleteEmpleado.as_view(), name='DeleteE'),

    path('list/Bitacora/', views.Bitacora.as_view(), name="Bitacora"),
    path('Detail/Bitacora/<int:pk>/', views.DetailBitacora.as_view(), name='DetailBi'),
    path('Create/Bitacora/', views.CreateBitacora.as_view(), name='CreateBi'),
    path('Update/Bitacora/<int:pk>/', views.UpdateBitacora.as_view(), name='UpdateBi'),
    path('Delete/Bitacora/<int:pk>/', views.DeleteBitacora.as_view(), name='DeleteBi'),
    
]

Cuatri 3/Portafolio2/Avance2/core/forms.py
from django import forms
from . import models
# Areas de Trabajos
class CreateAreaTrabajo(forms.ModelForm):
    class Meta:
        model = models.Areasdetrabajo
        fields = [
            'nombre'
        ] 
        
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
        }



class UpdateAreaTrabajo(forms.ModelForm):
    class Meta:
        model = models.Areasdetrabajo
        fields = [
            'nombre'
        ] 
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
        
# Empleados

class CreateEmpleado(forms.ModelForm):
    class Meta:
        model = models.Empleados
        fields = [
            'nombrepila',
            'primerapellido',
            'segundoapellido',
            'dircalle',
            'dirnumero',
            'dircolonia',
            'numtel',
            'horario',
            'jefearea',
            'areadetrabajo',
            'puesto',
        ]

        widgets = {
            'nombrepila': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el nombre de pila"}),
            'primerapellido': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el primer apellido"}),
            'segundoapellido': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el segundo apellido"}),
            'dircalle': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el nombre de la calle"}),
            'dirnumero': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el numero de direccion"}),
            'dircolonia': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el nombre de la colonia"}),
            'numtel': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el numero de telefono"}),
            'horario': forms.TimeInput(attrs={'class': 'form-control', "placeholder":"ingresa el horario"}),
            'jefearea': forms.Select(attrs={'class': 'form-control', "placeholder":" ingresa el jefe de area"}),
            'areadetrabajo': forms.Select(attrs={'class': 'form-control', "placeholder":"ingresa el area de trabajo"}),
            'puesto': forms.Select(attrs={'class': 'form-control', "placeholder":"ingresa el puesto"}),
        }



class UpdateEmpleado(forms.ModelForm):
    class Meta:
        model = models.Empleados
        fields = [
            'nombrepila',
            'primerapellido',
            'segundoapellido',
            'dircalle',
            'dirnumero',
            'dircolonia',
            'numtel',
            'horario',
            'jefearea',
            'areadetrabajo',
            'puesto',
        ]

        widgets = {
            'nombrepila': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el nombre de pila"}),
            'primerapellido': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el primer apellido"}),
            'segundoapellido': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el segundo apellido"}),
            'dircalle': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el nombre de la calle"}),
            'dirnumero': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el numero de direccion"}),
            'dircolonia': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el nombre de la colonia"}),
            'numtel': forms.TextInput(attrs={'class': 'form-control', "placeholder":"Escribe el numero de telefono"}),
            'horario': forms.TimeInput(attrs={'class': 'form-control', "placeholder":"ingresa el horario"}),
            'jefearea': forms.Select(attrs={'class': 'form-control', "placeholder":" ingresa el jefe de area"}),
            'areadetrabajo': forms.Select(attrs={'class': 'form-control', "placeholder":"ingresa el area de trabajo"}),
            'puesto': forms.Select(attrs={'class': 'form-control', "placeholder":"ingresa el puesto"}),
        }
        
# Bitacoras

class CreateBitacora(forms.ModelForm):
    class Meta:
        model = models.Bitacoras
        fields = [
            'titulo',
            'empleado',
            'metas',
        ] 
        
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'empleado': forms.Select(attrs={'class': 'form-control'}),
            'metas': forms.Select(attrs={'class': 'form-control'}),
        }



class UpdateBitacora(forms.ModelForm):
    class Meta:
        model = models.Bitacoras
        fields = [
            'titulo',
            'empleado',
            'metas',
        ] 
        
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'empleado': forms.Select(attrs={'class': 'form-control'}),
            'metas': forms.Select(attrs={'class': 'form-control'}),
        }
        

Cuatri 3/Portafolio2/Avance2/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from . import models
from . import forms

# Create your views here.
class Index(generic.View):
    template_name = 'core/Index.html'
    context = {}
    def get(self, request):
        self.context = {
            "Areas": models.Areasdetrabajo.objects.all(),
            "Empleados": models.Empleados.objects.all(),
            "Bitacoras": models.Bitacoras.objects.all()
        }
        return render(request, self.template_name, self.context)


# Areas de trabajos

class AreasTrabajo(generic.ListView):
    template_name = 'core/Areas_Trabajo/Area_Trabajo.html'
    model = models.Areasdetrabajo
    
    
    
class DetailAreasTrabajo(generic.DetailView):
    model=models.Areasdetrabajo
    template_name='core/Areas_Trabajo/Detail_Area_Trabajo.html'
    context = {}
    def get(self, request, pk):
        areaTrabajo = models.Areasdetrabajo.objects.get(numero=pk)
        self.context = {
            "Area": areaTrabajo
        }
        return render(request,  self.template_name, self.context)
    
class CreateAreaTrabajo(generic.CreateView):
    template_name = 'core/Areas_Trabajo/Create_Area_Trabajo.html'
    model = models.Areasdetrabajo
    form_class = forms.CreateAreaTrabajo
    success_url = reverse_lazy('core:AreasTrabajo')
    
class UpdateAreaTrabajo(generic.UpdateView):
    template_name = 'core/Areas_Trabajo/Update_Area_Trabajo.html'
    model = models.Areasdetrabajo
    form_class = forms.UpdateAreaTrabajo
    success_url = reverse_lazy("core:AreasTrabajo")

class DeleteAreaTrabajo(generic.DeleteView):
    template_name = 'core/Areas_Trabajo/Delete_Area_Trabajo.html'
    model = models.Areasdetrabajo
    success_url = reverse_lazy("core:AreasTrabajo")
    
    
    

# Empleados

class Empleado(generic.ListView):
    template_name = 'core/Empleados/Empleados.html'
    model = models.Empleados
    
    
       
class DetailEmpleado(generic.DetailView):
    model=models.Empleados
    template_name='core/Empleados/Detail_Empleado.html'
    context = {}
    def get(self, request, pk):
        empleado = models.Empleados.objects.get(numero=pk)
        self.context = {
            "Empleado": empleado
        }
        return render(request,  self.template_name, self.context)   
    
class CreateEmpleado(generic.CreateView):
    template_name = 'core/Empleados/Create_Empleado.html'
    model = models.Empleados
    form_class = forms.CreateEmpleado
    success_url = reverse_lazy('core:Empleados')
    
class UpdateEmpleado(generic.UpdateView):
    template_name = 'core/Empleados/Update_Empleado.html'
    model = models.Empleados
    form_class = forms.UpdateEmpleado
    success_url = reverse_lazy("core:Empleados")

class DeleteEmpleado(generic.DeleteView):
    template_name = 'core/Empleados/Delete_Empleado.html'
    model = models.Empleados
    success_url = reverse_lazy("core:Empleados")
    
    
    
# Bitacoras

class Bitacora(generic.ListView):
    template_name = 'core/Bitacoras/Bitacora.html'
    model = models.Bitacoras
    
    
       
class DetailBitacora(generic.DetailView):
    model=models.Bitacoras
    template_name='core/Bitacoras/Detail_Bitacora.html'
    context = {}
    def get(self, request, pk):
        bitacora = models.Bitacoras.objects.get(numero=pk)
        self.context = {
            "Bitacora": bitacora
        }
        return render(request,  self.template_name, self.context)
    
class CreateBitacora(generic.CreateView):
    template_name = 'core/Bitacoras/Create_Bitacora.html'
    model = models.Bitacoras
    form_class = forms.CreateBitacora
    success_url = reverse_lazy('core:Bitacora')
    
class UpdateBitacora(generic.UpdateView):
    template_name = 'core/Bitacoras/Update_Bitacora.html'
    model = models.Bitacoras
    form_class = forms.UpdateBitacora
    success_url = reverse_lazy("core:Bitacora")

class DeleteBitacora(generic.DeleteView):
    template_name = 'core/Bitacoras/Delete_Bitacora.html'
    model = models.Bitacoras
    success_url = reverse_lazy("core:Bitacora")


    
    
    

Cuatri 3/Portafolio2/Avance2/templates/core/Areas_Trabajo/Area_Trabajo.html
{% extends "base/base.html" %}

{% block title %}Lista de Áreas de Trabajo{% endblock %}

{% block content %}
<br>
<h1>Lista de Áreas de Trabajo</h1>

    {% if object_list %}
    <hr>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
          {% for Area in object_list %}
            <tr>
              <td>{{ Area.numero }}</td>
              <td>{{ Area.nombre }}</td>
              <td><a href="{% url 'core:DetailAT' pk=Area.numero %}" class="btn btn-outline-primary"> Details </a></td>
              <td><a href="{% url 'core:DeleteAT' pk=Area.numero %}" class="btn btn-outline-danger"> Delete </a></td>
              <td><a href="{% url 'core:UpdateAT' pk=Area.numero %}" class="btn btn-outline-warning"> Update </a></td>
            </tr>
          {% empty %}
          <li>No hay táreas de trabajo disponibles.</li>
          {% endfor %}
        </tbody>
    </table>
    {% else %}
    <br>
    <hr>
    <li>No hay bitacoras disponibles.</li>
    <hr>
    <br>
    {% endif %}
    <a href="{% url 'core:CreateAT' %}" class="btn btn-outline-success form-control">Crear una nueva Area de Trabajo</a> 

{% endblock content %}

Cuatri 3/Portafolio2/Avance2/templates/core/Areas_Trabajo/Create_Area_Trabajo.html
{% extends "base/base.html" %}

{% block title %}Crear Área de Trabajo{% endblock %}

{% block content %}
  <h1>Crear Área de Trabajo</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
    <a href="{% url 'core:AreasTrabajo' %}" class="btn btn-success">Volver a la lista de áreas de trabajo</a>
  </form>
  
{% endblock %}

Cuatri 3/Portafolio2/Avance2/templates/core/Areas_Trabajo/Delete_Area_Trabajo.html
{% extends "base/base.html" %}

{% block title %}Eliminar Área de Trabajo{% endblock %}

{% block content %}
  <h1>Eliminar Área de Trabajo</h1>
  <p>¿Estás seguro de que deseas eliminar esta área de trabajo?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:AreasTrabajo' %}" class="btn btn-warning">Volver a la lista de áreas de trabajo</a>
  </form>
  
{% endblock %}

Cuatri 3/Portafolio2/Avance2/templates/core/Areas_Trabajo/Detail_Area_Trabajo.html
{% extends "base/base.html" %}

{% block title %} Detalles del Área de Trabajo: {{ Area.nombre }} {% endblock %}

{% block content %}
  <h1>Detalles del Área de Trabajo</h1>
  <p><strong>Nombre del Área:</strong> {{ Area.nombre }}</p>
  <!-- Agrega aquí más detalles si es necesario -->
  <a href="{% url 'core:AreasTrabajo' %}" class="btn btn-outline-warning form-control">Volver a la lista de áreas de trabajo</a>
{% endblock %}

Cuatri 3/Portafolio2/Avance2/templates/core/Areas_Trabajo/Update_Area_Trabajo.html
{% extends "base/base.html" %}

{% block title %}Actualizar Área de Trabajo{% endblock %}

{% block content %}
  <h1>Actualizar Área de Trabajo</h1>
  <form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-outline-primary">Guardar Cambios</button>
    <a href="{% url 'core:AreasTrabajo' %}" class="btn btn-outline-warning">Volver a la lista de áreas de trabajo</a>
  </form>
  
{% endblock %}