Cuatri 3/Portafolio2/Examen2/nfl_pr/core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    
]

Cuatri 3/Portafolio2/Examen2/nfl_pr/home/urls.py
from django.urls import path
from home import views
from .views import (
    CityWithTeams, TeamStadium,
    CityTeams,
)

app_name = "home"
urlpatterns = [

   path('ciudad/', views.CityIndex.as_view(), name='ciudadindex'),
   path('ciudad/new/', views.NewCiudad.as_view(), name='ciudad_new'),
   path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='ciudad_detail'),
   path('ciudad/<int:pk>/edit/', views.UpdateCiudad.as_view(), name='ciudad_edit'),
   path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='ciudad_delete'),

   path('estadio/', views.StadiumIndex.as_view(), name='estadioindex'),
   path('estadio/new/', views.NewEstadio.as_view(), name='estadio_new'),
   path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='estadio_detail'),
   path('estadio/<int:pk>/edit/', views.UpdateEstadio.as_view(), name='estadio_edit'),
   path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='estadio_delete'),
   
   path('equipo/', views.TeamIndex.as_view(), name='equipoindex'),
   path('equipo/', views.EquipoIndex.as_view(), name="teamindex"),
   path('equipo/new/', views.NewEquipo.as_view(), name='equipo_new'),
   path('equipo/<int:pk>/', views.DetailEquipo.as_view(), name='equipo_detail'),
   path('equipo/<int:pk>/edit/', views.UpdateEquipo.as_view(), name='equipo_edit'),
   path('equipo/<int:pk>/delete/', views.DeleteEquipo.as_view(), name='equipo_delete'),


   path('', views.Index.as_view(), name='index'),

   path('equipo/citywithteams/', CityWithTeams.as_view(), name='cityWithTeams'),
   path('equipo/teamstadium/', TeamStadium.as_view(), name='teamsStadium'),
   path('equipo/cityteams/', CityTeams.as_view(), name='cityTeams'),
]

Cuatri 3/Portafolio2/Examen2/nfl_pr/nfl_pr/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

Cuatri 3/Portafolio2/Examen2/nfl_pr/home/models.py
from django.db import models

#MODEL CITY
class Ciudad(models.Model):
    id_ciudad = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name

#MODEL STADIUM
class Estadio(models.Model):
    id_estadio = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name

#MODEL TEAM
class Equipo(models.Model):
    id_equipo = models.AutoField(primary_key=True)
    name = models.CharField(max_length=80)
    city = models.ForeignKey(Ciudad, on_delete=models.CASCADE, null=True)
    stadium = models.ForeignKey(Estadio, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

Cuatri 3/Portafolio2/Examen2/nfl_pr/home/forms.py
from django import forms
from .models import Equipo, Ciudad, Estadio

#FORM EQUIPO
class UpdateEquipoForm(forms.ModelForm):
    city = forms.ModelChoiceField(queryset=Ciudad.objects.all(), required=False)
    stadium = forms.ModelChoiceField(queryset=Estadio.objects.all(), required=False)

    class Meta:
        model = Equipo
        fields = ['name', 'city', 'stadium']


class NewEquipoForm(forms.ModelForm):
    city = forms.ModelChoiceField(queryset=Ciudad.objects.all(), required=False)
    stadium = forms.ModelChoiceField(queryset=Estadio.objects.all(), required=False)

    class Meta:
        model = Equipo
        fields = ['name', 'city', 'stadium']


#FORM CIUDAD
class UpdateCiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["id_ciudad", "name"]


class NewCiudadForm(forms.ModelForm):
    class Meta:
        model = Ciudad
        fields = ["id_ciudad", "name"]


#FORM ESTADIO
class UpdateEstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["id_estadio", "name"]

class NewEstadioForm(forms.ModelForm):
    class Meta:
        model = Estadio
        fields = ["id_estadio", "name"]

Cuatri 3/Portafolio2/Examen2/nfl_pr/home/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from .models import Equipo, Ciudad, Estadio
from .forms import UpdateEquipoForm, NewEquipoForm, UpdateCiudadForm, NewCiudadForm, UpdateEstadioForm, NewEstadioForm



#Ciudades con equipos:
class cteams(generic.View):
    template_name = "home/cteams.html"
    context = {}

    def get(self, request):
        self.context = {
            "ciudades": Ciudad.objects.filter(equipo__isnull=False).distinct()
        }
        return render(request, self.template_name, self.context)


#Que equipo juega en que estadio:
class estadioe(generic.View):
    template_name = "home/estadioe.html"
    context = {}

    def get(self, request):
        self.context = {
            "teams": Equipo.objects.select_related('stadium')
        }
        return render(request, self.template_name, self.context)


#Que equipos tienen una ciudad:
class cequipos(generic.View):
    template_name = "home/cequipos.html"
    context = {}

    def get(self, request):
        self.context = {
            "ciudades": Ciudad.objects.exclude(equipo__isnull=True).distinct()
        }
        return render(request, self.template_name, self.context)

#DETAIL
class DetailEquipo(generic.DetailView):
    template_name = "home/detail_equipo.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "equipo": Equipo.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


#DELETE
class DeleteEquipo(generic.DeleteView):
    template_name = "home/delete_equipo.html"
    model = Equipo
    success_url = reverse_lazy("home:equipoindex") 


#CREATE
class NewEquipo(generic.CreateView):
    template_name = 'home/new_equipo.html'
    model = Equipo
    form_class = NewEquipoForm
    success_url = reverse_lazy('home:teamindex')


#UPDATE
class UpdateEquipo(generic.UpdateView):
    template_name = 'home/update_equipo.html'
    model = Equipo
    form_class = UpdateEquipoForm
    success_url = reverse_lazy("home:teamindex")


#PLANTILLA HOME/TEAMINDEX
class TeamIndex(generic.View):
    template_name = "home/teamindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "equipos": Equipo.objects.all()
        }
        return render(request, self.template_name, self.context)


#PLANTILLA BASE/EQUIPOINDEX
class EquipoIndex(generic.View):
    template_name = "base/equipoindex.html"
    context = {}

    def get(self, request):
        return render(request, self.template_name, self.context)


#///////////////////////////////////////////////////////////////////////////
#INDEX
class Index(generic.View):
    template_name = "base/lobby.html"
    context = {}

    def get(self, request):
        return render(request, self.template_name, self.context)
#//////////////////////////////////////////////////////////////////////////


#CIUDAD

#DETAIL
class DetailCiudad(generic.DetailView):
    template_name = "home/detail_ciudad.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "ciudad": Ciudad.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


#DELETE
class DeleteCiudad(generic.DeleteView):
    template_name = "home/delete_ciudad.html"
    model = Ciudad
    success_url = reverse_lazy("home:ciudadindex") 


#CREATE
class NewCiudad(generic.CreateView):
    template_name = 'home/new_ciudad.html'
    model = Ciudad
    form_class = NewCiudadForm
    success_url = reverse_lazy('home:ciudadindex')


#UPDATE
class UpdateCiudad(generic.UpdateView):
    template_name = 'home/update_equipo.html'
    model = Ciudad
    form_class = UpdateCiudadForm
    success_url = reverse_lazy("home:ciudadindex")



#PLANTILLA HOME/TEAMINDEX
class CityIndex(generic.View):
    template_name = "home/cityindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "ciudads": Ciudad.objects.all()
        }
        return render(request, self.template_name, self.context)


#///////////////////////////////////////////////////////////////////////////
#ESTADIO

#DETAIL
class DetailEstadio(generic.DetailView):
    template_name = "home/detail_estadio.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "estadio": Estadio.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


#DELETE
class DeleteEstadio(generic.DeleteView):
    template_name = "home/delete_estadio.html"
    model = Estadio
    success_url = reverse_lazy("home:estadioindex") 


#CREATE
class NewEstadio(generic.CreateView):
    template_name = 'home/new_estadio.html'
    model = Estadio
    form_class = NewEstadioForm
    success_url = reverse_lazy('home:estadioindex')


#UPDATE
class UpdateEstadio(generic.UpdateView):
    template_name = 'home/update_estadio.html'
    model = Estadio
    form_class = UpdateEstadioForm
    success_url = reverse_lazy("home:estadioindex")



#PLANTILLA HOME/TEAMINDEX
class StadiumIndex(generic.View):
    template_name = "home/stadiumindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "estadios": Estadio.objects.all()
        }
        return render(request, self.template_name, self.context)

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/cequipos.html
{% extends 'base/equipoindex.html' %}

{% block content %}
  <h2>Equipos por ciudad</h2>
  {% for ciudad in ciudades %}
    <h3>{{ ciudad.name }}</h3>
    <ul>
    {% for equipo in ciudad.equipo_set.all %}
      <li>{{ equipo.name }}</li>
    {% empty %}
      <li>No hay equipos en esta ciudad.</li>
    {% endfor %}
    </ul>
  {% empty %}
    <li>No hay ciudades registradas.</li>
  {% endfor %}
{% endblock %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/cityindex.html
{% extends 'base/equipoindex.html' %}
{% block title %} Ciudades {% endblock title %}

{% block content %}
    <a href="{% url 'home:ciudad_new' %}" class="btn btn-outline-info">Nueva Ciudad</a>
    
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>Nombre de la Ciudad</th>
        </thead>
        <tbody>
            {% for ciudad in ciudads %}
                <tr>
                    <td>{{ ciudad.id_ciudad }}</td>
                    <td>{{ ciudad.name }}</td>
                    <td><a href="{% url 'home:ciudad_detail' ciudad.id_ciudad %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'home:ciudad_delete' ciudad.id_ciudad %}" class="btn btn-outline-danger">Delete</a></td>
                    <td><a href="{% url 'home:ciudad_edit' ciudad.id_ciudad %}" class="btn btn-outline-warning">Update</a></td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/cteams.html
{% extends 'base/equipoindex.html' %}

{% block content %}
  <h2>Ciudades con equipos</h2>
  <ul>
  {% for ciudad in ciudades %}
    <li>{{ ciudad.name }}</li>
  {% empty %}
    <li>No hay ciudades con equipos.</li>
  {% endfor %}
  </ul>
{% endblock %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/delete_equipo.html
{% extends 'base/equipoindex.html' %}

{% block title %}Delete Equipo View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas eliminar este equipo: {{ object }}?
        <a href="{% url 'home:equipoindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/delete_estadio.html
{% extends 'base/equipoindex.html' %}

{% block title %}Delete Estadio View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas eliminar esta ciudad: {{ object }}?
        <a href="{% url 'home:estadioindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/detail_equipo.html
{% extends 'base/equipoindex.html' %}
{% block title %}Detail Equipo View{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ equipo.name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Category was created by: <strong>{{ equipo.id_equipo }}</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the The city is is: <strong><code>{{ equipo.city }}</code></strong>, though the transition does limit overflow. <a href="{% url 'home:equipoindex' %}" class="btn btn-link">back to index</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/detail_estadio.html
{% extends 'base/equipoindex.html' %}
{% block title %}Detail Estadio View{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ estadio.name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Category was created by: <strong>{{ estadio.id_estadio }}</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the The stadium is: <strong><code>{{ estadio.name }}</code></strong>, though the transition does limit overflow. <a href="{% url 'home:estadioindex' %}" class="btn btn-link">back to index</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/estadioe.html
{% extends 'base/equipoindex.html' %}

{% block content %}
  <h2>Equipos y estadios</h2>
  <ul>
  {% for equipo in teams %}
    <li>{{ equipo.name }} juega en {{ equipo.stadium.name }}</li>
  {% empty %}
    <li>No hay equipos registrados.</li>
  {% endfor %}
  </ul>
{% endblock %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/new_ciudad.html
{% extends 'base/equipoindex.html' %}

{% block title %}New Ciudad View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:ciudadindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">New Ciudad</button>
    </form>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/new_equipo.html
{% extends 'base/equipoindex.html' %}

{% block title %}New Equipo View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:equipoindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">New Equipo</button>
    </form>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/new_estadio.html
{% extends 'base/equipoindex.html' %}

{% block title %}New Estadio View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:estadioindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">New Estadio</button>
    </form>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/teamindex.html
{% extends 'base/equipoindex.html' %}
{% block title %} Equipos {% endblock title %}

{% block content %}
    <a href="{% url 'home:equipo_new' %}" class="btn btn-outline-info">Nuevo Equipo</a>
    
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>Equipo</th>
            <th>Ciudad</th>
            <th>Estadio</th>
        </thead>
        <tbody>
            {% for equipo in equipos %}
                <tr>
                    <td>{{ equipo.id_equipo }}</td>
                    <td>{{ equipo.name }}</td>
                    <td>{{ equipo.city }}</td>
                    <td>{{ equipo.stadium }}</td>
                    <td><a href="{% url 'home:equipo_detail' equipo.id_equipo %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'home:equipo_delete' equipo.id_equipo %}" class="btn btn-outline-danger">Delete</a></td>
                    <td><a href="{% url 'home:equipo_edit' equipo.id_equipo %}" class="btn btn-outline-warning">Update</a></td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/update_ciudad.html
{% extends 'base/equipoindex.html' %}

{% block title %}Update Ciudad View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:ciudadindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-warning">Update</button>
    </form>
{% endblock content %}

Cuatri 3/Portafolio2/Examen2/nfl_pr/templates/home/update_estadio.html
{% extends 'base/equipoindex.html' %}

{% block title %}Update Estadio View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:estadioindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-warning">Update</button>
    </form>
{% endblock content %}