Cuatri 3/Portafolio2/Avance2/System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
]

Cuatri 3/Portafolio2/Avance2/core/urls.py
from django.urls import path
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    
    path('list/Areas-de-Trabajo/', views.AreasTrabajo.as_view(), name="AreasTrabajo"),
    path('Detail/Areas-de-Trabajo/<int:pk>/', views.DetailAreasTrabajo.as_view(), name='DetailAT'),
    path('Create/Areas-de-Trabajo/', views.CreateAreaTrabajo.as_view(), name='CreateAT'),
    path('Update/Areas-de-Trabajo/<int:pk>/', views.UpdateAreaTrabajo.as_view(), name='UpdateAT'),
    path('Delete/Areas-de-Trabajo/<int:pk>/', views.DeleteAreaTrabajo.as_view(), name='DeleteAT'),

    path('list/Empleados/', views.Empleado.as_view(), name="Empleados"),
    path('Detail/Empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='DetailE'),
    path('Create/Empleado/', views.CreateEmpleado.as_view(), name='CreateE'),
    path('Update/Empleado/<int:pk>/', views.UpdateEmpleado.as_view(), name='UpdateE'),
    path('Delete/Empleado/<int:pk>/', views.DeleteEmpleado.as_view(), name='DeleteE'),

    path('list/Bitacora/', views.Bitacora.as_view(), name="Bitacora"),
    path('Detail/Bitacora/<int:pk>/', views.DetailBitacora.as_view(), name='DetailBi'),
    path('Create/Bitacora/', views.CreateBitacora.as_view(), name='CreateBi'),
    path('Update/Bitacora/<int:pk>/', views.UpdateBitacora.as_view(), name='UpdateBi'),
    path('Delete/Bitacora/<int:pk>/', views.DeleteBitacora.as_view(), name='DeleteBi'),
    
]

Cuatri 3/Portafolio2/Avance2/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title%}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">Empresa</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
                          </li>                          
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Areas de Trabajo
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:CreateAT' %}">New Areas de Trabajo</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:AreasTrabajo' %}">List Areas de Trabajo</a></li>
                              <li><hr class="dropdown-divider"></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Empleados
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:CreateE' %}">New Empleados</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:Empleados' %}">List Empleados</a></li>
                              <li><hr class="dropdown-divider"></li>
                            </ul>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Bitacoras
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'core:CreateBi' %}">New Bitacoras</a></li>
                              <li><a class="dropdown-item" href="{% url 'core:Bitacora' %}">List Bitacoras</a></li>
                              <li><hr class="dropdown-divider"></li>
                            </ul>
                          </li>                   
                        </ul>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>

        <div class="row">
                <div class="col">
                    {% block content %}
                    {% endblock content %}
                </div>
        </div>

        <div class="row">
            <div class="col">

            </div>
            <div class="col">

            </div>
        </div>
    </div>
    

   
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>